### ISSUE TITLE
Sound effects don't work in release build

### ISSUE THREAD

**Issue by TheSamsai** [egordorichev/Lens#219]
Hi! I tried building the game (thanks for the instructions BTW, some of us are pretty bad at C# development) and I tried it a bit on stream yesterday. Sadly I haven't been able to get the sound effects to work. The music works just fine, just the SFX files seem to not be loaded.

In the console the game reports that the SFX are not found:

```
Sound effect unlock was not found! 1:03:17 GetSfx() <= Emit()
```

I poked around in the source code and found that it seemingly tries to load the SFX from Desktop/bin/Release/Content/bin/Sfx which I noticed was missing. After copying the directory from BurningKnight/Content/Sfx it found the folder but seemingly didn't find the files. I am not quite experienced enough in C# programming to effectively debug this further, so I'm hoping that this issue might allow you to track it down.

Thanks for open sourcing the game, it seems quite fun. Might throw some buckaroos your way on Steam/Itch when I get some disposable income.

**Comment by egordorichev** [comment]
Hello!

Sorry, this is totally my fault. I never build the release configuration on my machines (I use github actions for an automatic build). So I forgot to mention, that you gotta install MonoGame Content Pipeline tool and compile the assets (raw sfx -> `.xnb`).

If you are on Linux, you can get it via:

```sh
wget https://github.com/MonoGame/MonoGame/releases/download/v3.7.1/monogame-sdk.run
chmod +x monogame-sdk.run
sudo ./monogame-sdk.run
```

Otherwise, find a binary on the monogame website. After that open `BurningKnight/Content/Content.mgcb` in the tool and hit build.

![image](https://user-images.githubusercontent.com/7851390/96409702-5cb22700-11ee-11eb-8586-0afe349f1473.png)
If you are on Linux, ignore shader compilation errors, prebuild shaders (via a Windows machine) are already in the repo.

This should resolve it! Pushing a tiny fix to `.csproj` right now.
